# Generated by Django 4.2.10 on 2026-02-02 01:14

from django.db import migrations, models
import django.db.models.deletion
import pgvector.django
from pgvector.django import VectorExtension
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='papers/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('full_text', models.TextField(blank=True)),
                ('sections', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('task_type', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('result', models.JSONField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Task statuses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Methodology',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datasets', models.JSONField(blank=True, default=list)),
                ('model', models.JSONField(blank=True, default=dict)),
                ('metrics', models.JSONField(blank=True, default=list)),
                ('results', models.JSONField(blank=True, default=dict)),
                ('summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paper', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='methodology', to='papers.paper')),
            ],
            options={
                'verbose_name_plural': 'Methodologies',
            },
        ),
        migrations.CreateModel(
            name='GapAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('methodological_gaps', models.JSONField(default=list)),
                ('dataset_limitations', models.JSONField(default=list)),
                ('evaluation_gaps', models.JSONField(default=list)),
                ('novel_directions', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('papers', models.ManyToManyField(related_name='gap_analyses', to='papers.paper')),
            ],
            options={
                'verbose_name_plural': 'Gap analyses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SectionSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section_name', models.CharField(max_length=100)),
                ('summary', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_summaries', to='papers.paper')),
            ],
            options={
                'ordering': ['section_name'],
                'unique_together': {('paper', 'section_name')},
            },
        ),
        migrations.CreateModel(
            name='Embedding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section_name', models.CharField(blank=True, max_length=100)),
                ('text', models.TextField()),
                ('embedding', pgvector.django.VectorField(dimensions=384)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='papers.paper')),
            ],
            options={
                'indexes': [models.Index(fields=['paper', 'section_name'], name='papers_embe_paper_i_f87c38_idx')],
            },
        ),
    ]
