# Generated by Django 4.2.10 on 2026-02-02 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
