# Generated by Django 4.2.10 on 2026-02-02 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0002_paper_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='task_ids',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
