# Generated by Django 4.2.10 on 2026-02-02 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0003_paper_task_ids'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sectionsummary',
            options={'ordering': ['order_index', 'created_at']},
        ),
        migrations.AddField(
            model_name='sectionsummary',
            name='order_index',
            field=models.IntegerField(default=0),
        ),
    ]
