# Generated by Django 4.2.10 on 2026-02-03 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0004_alter_sectionsummary_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='authors',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='title',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
