# Generated by Django 4.2.10 on 2026-02-03 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0005_paper_authors_paper_notes_paper_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='global_summary',
            field=models.TextField(blank=True),
        ),
    ]
