# Generated by Django 4.2.10 on 2026-02-05 01:09

from django.db import migrations

def delete_existing_embeddings(apps, schema_editor):
    Embedding = apps.get_model('papers', 'Embedding')
    Embedding.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0006_paper_global_summary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GapAnalysis',
        ),
        migrations.RunPython(delete_existing_embeddings),
    ]
