# Generated by Django 4.2.10 on 2026-02-05 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0006_paper_global_summary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GapAnalysis',
        ),
    ]
