# Generated by Django 4.2.10 on 2026-02-06 06:17

from django.db import migrations
import pgvector.django


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0007_delete_gapanalysis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embedding',
            name='embedding',
            field=pgvector.django.VectorField(dimensions=768),
        ),
    ]
