# Generated by Django 4.2.10 on 2026-02-06 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0008_alter_embedding_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='session_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
