# Generated by Django 4.2.10 on 2026-02-07 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0009_paper_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='journal',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='paper',
            name='year',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='paper',
            name='title',
            field=models.TextField(blank=True),
        ),
    ]
