# Generated by Django 4.2.10 on 2026-02-07 23:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0010_paper_journal_paper_year_alter_paper_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(db_index=True, max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('papers', models.ManyToManyField(blank=True, related_name='collections', to='papers.paper')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('session_id', 'name')},
            },
        ),
    ]
